---
- name: Install redis
  become: true
  apt:  pkg=redis-server state=latest

- name: Listen on all interfaces
  become: true
  lineinfile: dest=/etc/redis/redis.conf regexp="^bind" "line=#bind"
  notify: restart redis
