---
  - name: Update apt
    become: true
    apt:  update_cache=yes

  - name: Install system packages
    become: true
    apt:  pkg={{ item }} state=latest
    with_items:
      - curl
      - wget
      - build-essential
      - python-software-properties

  - name: Add ppa repository
    become: true
    apt_repository: repo=ppa:ondrej/{{ php_ppa }}

  - name: Update apt again
    become: true
    apt:  update_cache=yes

  - name: Install extra packages
    become: true
    apt:  pkg={{ item }} state=latest
    with_items: "{{ sys_packages }}"

  - name: Add Env variables
    lineinfile: dest=/home/{{ansible_ssh_user}}/.bashrc line="export {{ item.key }}={{ item.value }}"
    with_items: "{{ bash_env }}"
