---
- name:    Download PHPUnit
  become:    false
  get_url:
    url: https://phar.phpunit.de/phpunit.phar
    dest: /tmp/phpunit.phar

- name:    Add executable permissions to PHPUnit
  file: path=/tmp/phpunit.phar mode=0755

- name:    Move PHPunit to /usr/local/bin
  become:    true
  command: mv /tmp/phpunit.phar /usr/local/bin/phpunit