---
- hosts: all
  become: true
  vars:
    doc_root: /var/www/web
    sys_packages:
      - mcrypt
      - vim
    php_packages:
      - { name: dev, package: php5-dev }
      - { name: pear, package: php-pear }
      - { name: xdebug, package: php5-xdebug }
      - { name: curl, package: php5-curl }
      - { name: mcrypt, package: php5-mcrypt }
      - { name: mysql, package: php5-mysql }
      - { name: redis, package: php5-redis }
      - { name: apc, package: php-apc }
      - { name: memcached, package: php5-memcached }
      - { name: sqlite, package: php5-sqlite }
      - { name: gd, package: php5-gd }
      - { name: xdebug, package: php5-xdebug }
    php_extensions:
      - { name: "jsmin", package: "pecl.php.net/jsmin-beta" }
      - { name: "mongo", package: "pecl.php.net/mongo" }
      - { name: "xhprof", package: "pecl.php.net/xhprof-beta" }
    php_env:
      - { key: "SYMFONY__VAGRANT", value: "true"}
    bash_env:
      - { key: "SYMFONY__VAGRANT", value: "1"}
    php_ppa: php5
    nodejs:
      version: _5.x
      packages: [casperjs, phantomjs, bower, gulp]
    xdebug_key: ~
  roles:
    - init
    - nginx
    - php5-fpm
    - php5-cli
    - php5-common
    - composer
    - phpunit
    - mysql
    - mongo
    - git
    - curl
    - sqlite
    - wget
    - rabbitmq
    - redis
    - memcached
    - nodejs
