---
- name: Install PHP packages
  become: true
  apt:  package={{ item.package }} state=latest
  with_items: "{{ php_packages }}"

- name: Enable PHP packages
  become: true
  command: /usr/sbin/php5enmod {{ item.name }} creates=/etc/php5/cli/conf.d/20-{{ item.name }}.ini
  with_items: "{{ php_packages }}"
  notify: restart php5-fpm

- name: Disable xdebug for cli for perf
  become: true
  file: path=/etc/php5/cli/conf.d/20-xdebug.ini state=absent

- name: Config xdebug
  become: true
  when: xdebug_key is defined
  blockinfile:
    dest: /etc/php5/mods-available/xdebug.ini
    block: |
      xdebug.remote_enable=true
      xdebug.remote_connect_back=true
      xdebug.idekey={{ xdebug_key }}

- name: Install PHP extensions
  become: true
  shell: echo "\n" | /usr/bin/pecl install {{ item.package }} creates=/usr/lib/php5/20121212/{{ item.name }}.so
  with_items: "{{ php_extensions }}"

- name: Configure PHP extensions
  become: true
  template: src=extension.tpl dest=/etc/php5/mods-available/{{ item.name }}.ini
  with_items: "{{ php_extensions }}"

- name: Enable PHP extensions
  become: true
  command: /usr/sbin/php5enmod {{ item.name }} creates=/etc/php5/cli/conf.d/20-{{ item.name }}.ini
  with_items: "{{ php_extensions }}"
  notify: restart php5-fpm
